ARG NODE_IMAGE=node:16.13.1-alpine

FROM $NODE_IMAGE AS base
RUN mkdir -p /app && chown node:node /app
WORKDIR /app/
USER node
RUN mkdir tmp

FROM base AS dependencies
COPY --chown=node:node ./package*.json ./
COPY --chown=node:node ./yarn.lock ./
RUN yarn install
COPY --chown=node:node . .

FROM base AS development
ENV NODE_ENV=development
COPY --chown=node:node ./package*.json ./
COPY --chown=node:node ./yarn.lock ./
RUN yarn install
CMD ["yarn", "dev", "-p"]
